name: Daily Auto Commit

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make a dummy change
        run: echo "Last auto commit: $(date)" > .autocommit.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .autocommit.txt
          git commit -m "Daily auto commit - $(date)"

      - name: Push changes
        run: git push
