name: Daily Auto Commit

on:
  schedule:
    - cron: "0 18 * * *"   # svaki dan u 18:00 UTC (20:00 po našem vremenu)
  workflow_dispatch:       # omogućava ručno pokretanje

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # omogućava push sa GITHUB_TOKEN

      - name: Commit random changes
        run: |
          git config user.name "Marko Đokić"
          git config user.email "mare160696@gmail.com"
          # generiši random broj od 1 do 10
          COMMITS=$(( ( RANDOM % 10 ) + 1 ))
          echo "Praviću $COMMITS commitova danas."
          for i in $(seq 1 $COMMITS); do
            echo "Auto commit $i at $(date)" > .autocommit.txt
            git add .autocommit.txt
            git commit -m "Auto commit $i - $(date)"
          done

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_PAT }}@github.com/maredjokic/PortfolioMarkoDjokic.git
          git push