name: Daily Auto Commit

permissions:
  contents: write  # omogućava push na repozitorijum

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check secret
        run: |
          if [ -z "${{ secrets.DAILY_ACTION_PATH }}" ]; then
            echo "Secret DAILY_ACTION_PATH nije postavljen!"
            exit 1
          else
            echo "Secret postoji i može se koristiti."
          fi

      - name: Commit random changes
        run: |
          git config user.name "Marko Đokić"
          git config user.email "mare160696@gmail.com"

          # Random broj commitova
          COMMITS=$(( ( RANDOM % 10 ) + 1 ))
          echo "Praviću $COMMITS commitova danas."

          git fetch origin
          git reset --hard origin/main
          for i in $(seq 1 $COMMITS); do
            # overwrite fajla svaki put
            echo "Auto commit $i at $(date)" > .autocommit.txt
            git add .autocommit.txt
            git commit -m "Auto commit $i - $(date)"
          done

          # Postavi remote sa PAT i forsiraj push
          git remote remove origin
          git remote add origin https://x-access-token:${{ secrets.DAILY_ACTION_PATH }}@github.com/maredjokic/PortfolioMarkoDjokic.git
          git push -f origin main

      - name: Verify push
        run: echo "Push završio. Proveri logove za status."
