name: Daily Random Commits

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Make random number of commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # generiši random broj od 1 do 10
          COMMITS=$(( ( RANDOM % 10 )  + 1 ))
          echo "Praviću $COMMITS commitova danas."

          for i in $(seq 1 $COMMITS); do
            echo "Auto commit $i at $(date)" > .autocommit.txt
            git add .autocommit.txt
            git commit -m "Auto commit $i - $(date)"
          done

      - name: Push changes
        run: git push
